// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoD6UowhnrgausysyRDOqJ7_8SEyaS-0A',
    appId: '1:331103672965:web:33497bb406574a0449e7ec',
    messagingSenderId: '331103672965',
    projectId: 'devaern-platform',
    authDomain: 'devaern-platform.firebaseapp.com',
    storageBucket: 'devaern-platform.firebasestorage.app',
    measurementId: 'G-MV39EGEDX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE04lGpZrCBksFqnnf7yKkgWwrhU-93XI',
    appId: '1:331103672965:android:f1ca6a70fb2e238d49e7ec',
    messagingSenderId: '331103672965',
    projectId: 'devaern-platform',
    storageBucket: 'devaern-platform.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWxURUZiwEfkFMdr3TUYJRmE1UVTW28mU',
    appId: '1:331103672965:ios:3a0f9092e6ed87ad49e7ec',
    messagingSenderId: '331103672965',
    projectId: 'devaern-platform',
    storageBucket: 'devaern-platform.firebasestorage.app',
    iosBundleId: 'com.example.devaern',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWxURUZiwEfkFMdr3TUYJRmE1UVTW28mU',
    appId: '1:331103672965:ios:3a0f9092e6ed87ad49e7ec',
    messagingSenderId: '331103672965',
    projectId: 'devaern-platform',
    storageBucket: 'devaern-platform.firebasestorage.app',
    iosBundleId: 'com.example.devaern',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoD6UowhnrgausysyRDOqJ7_8SEyaS-0A',
    appId: '1:331103672965:web:e8f0e94712fb85c149e7ec',
    messagingSenderId: '331103672965',
    projectId: 'devaern-platform',
    authDomain: 'devaern-platform.firebaseapp.com',
    storageBucket: 'devaern-platform.firebasestorage.app',
    measurementId: 'G-RD5CV5QGFL',
  );
}
